---

- name: Download and install kibana gpg public signing key
  rpm_key:
    key:   "{{ kibana_signing_key_url }}"
    state: present

- name: Add kibana yum repository
  template:
    src:   kibana.yum.repo.j2
    dest:  /etc/yum.repos.d/kibana.repo
    owner: root
    group: root
    mode:  0644

- name: Install kibana
  yum:
    name:  "kibana-{{ kibana_version|default('*') }}"
    state: present
