---

- name: Kibana Install
  include: "install-{{ ansible_os_family|lower }}.yml"

- name: Create kibana config file
  template: 
    src:   kibana.yml.j2
    dest:  "{{ kibana_conf_dir }}/kibana.yml"
    owner: "root"
    group: "root"
    mode:  0644
  notify: 
    - Restart kibana

- name: Create kibana default settings file
  template: 
    src:   etc.default.kibana.j2
    dest:  "/etc/default/kibana"
    owner: root
    group: root
    mode:  0644
  notify: 
    - Restart kibana
  
- name: Start kibana
  service: name=kibana enabled=yes state=started
